#!/bin/bash
echo"enter the source"
read sourc
echo"enter the dest"
read dest
REMOTE_USER="admin"
REMOTE_HOST"192.168.1.50"
scp "$sourc" "$REMOTE_USER@REMOTE_HOST:$dest"
if [ $? -eq 0 ]
then
        echo "successful"
else
        echo "not successful"
fi
